# Generated by Django 3.2.12 on 2022-03-04 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employee',
            new_name='employees',
        ),
    ]
